#!/usr/bin/env bash
set -euo pipefail

root="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
asset_dir="$root/assets/path"

command -v dot >/dev/null 2>&1 || {
  printf 'Graphviz dot is required.\n' >&2
  exit 1
}

for name in master-path l-lane career-expansion; do
  dot -Tsvg "$asset_dir/$name.dot" -o "$asset_dir/$name.svg.tmp"
  dot -Tpng -Gdpi=170 "$asset_dir/$name.dot" -o "$asset_dir/$name.png.tmp"
  NAME="$name" ASSET_DIR="$asset_dir" python3 - <<'PY'
from __future__ import annotations
import os
import re
from pathlib import Path
name = os.environ["NAME"]
asset = Path(os.environ["ASSET_DIR"])
svg_tmp = asset / f"{name}.svg.tmp"
svg = svg_tmp.read_text(encoding="utf-8")
# Graphviz emits a two-line SVG 1.1 doctype; remove it to avoid external DTD references.
svg = re.sub(r"<!DOCTYPE svg PUBLIC .*?>\s*", "", svg, count=1, flags=re.S)
svg = re.sub(r"<!-- Generated by graphviz.*?-->\s*", "", svg, flags=re.S)
(asset / f"{name}.svg").write_text(svg, encoding="utf-8", newline="\n")
svg_tmp.unlink()
(asset / f"{name}.png.tmp").replace(asset / f"{name}.png")
PY
  test -s "$asset_dir/$name.svg"
  test -s "$asset_dir/$name.png"
done

ASSET_DIR="$asset_dir" python3 - <<'PY'
from __future__ import annotations
import hashlib
import json
import os
from pathlib import Path
asset = Path(os.environ["ASSET_DIR"])

def digest(path: Path) -> str:
    return hashlib.sha256(path.read_bytes()).hexdigest()

manifest = {}
for name in ("master-path", "l-lane", "career-expansion"):
    manifest[name] = {
        "dot_sha256": digest(asset / f"{name}.dot"),
        "svg_sha256": digest(asset / f"{name}.svg"),
        "png_sha256": digest(asset / f"{name}.png"),
    }
(asset / "render-manifest.json").write_text(
    json.dumps(manifest, ensure_ascii=False, indent=2) + "\n",
    encoding="utf-8",
    newline="\n",
)
PY

printf 'rendered and fingerprinted PATH graphs\n'
